/**
 * CulinaryCraft - Comprehensive Recipe & Pantry Database
 * Features 25+ diverse recipes with complete ingredient profiles,
 * nutritional breakdown, culinary tags, cooking tips, and substitution suggestions.
 */

const COMMON_PANTRY_INGREDIENTS = [
  { name: "Tomato", category: "produce", icon: "🍅" },
  { name: "Onion", category: "produce", icon: "🧅" },
  { name: "Garlic", category: "produce", icon: "🧄" },
  { name: "Potato", category: "produce", icon: "🥔" },
  { name: "Egg", category: "dairy", icon: "🥚" },
  { name: "Cheese", category: "dairy", icon: "🧀" },
  { name: "Milk", category: "dairy", icon: "🥛" },
  { name: "Butter", category: "dairy", icon: "🧈" },
  { name: "Chicken Breast", category: "meat", icon: "🍗" },
  { name: "Ground Beef", category: "meat", icon: "🥩" },
  { name: "Bacon", category: "meat", icon: "🥓" },
  { name: "Pasta", category: "pantry", icon: "🍝" },
  { name: "Rice", category: "pantry", icon: "🍚" },
  { name: "Bread", category: "pantry", icon: "🍞" },
  { name: "Olive Oil", category: "pantry", icon: "🫒" },
  { name: "Mushroom", category: "produce", icon: "🍄" },
  { name: "Bell Pepper", category: "produce", icon: "🫑" },
  { name: "Spinach", category: "produce", icon: "🥬" },
  { name: "Lemon", category: "produce", icon: "🍋" },
  { name: "Avocado", category: "produce", icon: "🥑" },
  { name: "Carrot", category: "produce", icon: "🥕" },
  { name: "Broccoli", category: "produce", icon: "🥦" },
  { name: "Soy Sauce", category: "pantry", icon: "🥢" },
  { name: "Black Beans", category: "pantry", icon: "🥫" },
  { name: "Chickpeas", category: "pantry", icon: "🫘" },
  { name: "Flour", category: "pantry", icon: "🌾" },
  { name: "Sugar", category: "pantry", icon: "🧂" },
  { name: "Oats", category: "pantry", icon: "🥣" },
  { name: "Honey", category: "pantry", icon: "🍯" },
  { name: "Tofu", category: "meat", icon: "🧊" },
  { name: "Shrimp", category: "meat", icon: "🦐" },
  { name: "Salmon", category: "meat", icon: "🐟" },
  { name: "Heavy Cream", category: "dairy", icon: "🥛" },
  { name: "Cilantro", category: "produce", icon: "🌿" },
  { name: "Basil", category: "produce", icon: "🌱" },
  { name: "Ginger", category: "produce", icon: "🫚" },
  { name: "Corn", category: "produce", icon: "🌽" },
  { name: "Yogurt", category: "dairy", icon: "🍦" }
];

const INGREDIENT_SUBSTITUTIONS = {
  "heavy cream": "Whole milk + butter, Greek yogurt, or coconut cream",
  "sour cream": "Plain Greek yogurt or blended cottage cheese with lemon",
  "butter": "Olive oil, coconut oil, or applesauce (in baking)",
  "cheese": "Pecorino, sharp cheddar, mozzarella, or nutritional yeast",
  "parmesan": "Pecorino Romano, nutritional yeast, or aged sharp cheddar",
  "egg": "Flax egg (1 tbsp flaxseed + 3 tbsp water) or applesauce in baking",
  "eggs": "Flax egg (1 tbsp flaxseed + 3 tbsp water) or applesauce in baking",
  "milk": "Oat milk, almond milk, soy milk, or water with a pat of butter",
  "soy sauce": "Tamari (gluten-free), Worcestershire sauce, or coconut aminos",
  "breadcrumbs": "Crushed crackers, rolled oats, or cornflakes",
  "lemon": "Lime juice or a dash of apple cider vinegar",
  "honey": "Maple syrup, brown sugar, or agave nectar",
  "chicken breast": "Tofu, chickpeas, shrimp, or turkey breast"
};

const RECIPES_DATA = [
  {
    id: "rec-01",
    title: "Classic Spaghetti Aglio e Olio",
    category: "Dinner",
    cuisine: "Italian",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    calories: 420,
    macros: { protein: "12g", carbs: "62g", fat: "14g" },
    diet: ["Vegetarian"],
    rating: 4.9,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    description: "A traditional Roman late-night pasta masterpiece made with garlic gently sizzled in extra virgin olive oil, chili flakes, fresh parsley, and al dente pasta.",
    wasteReductionTip: "Save pasta cooking water! The starchy water emulsifies with olive oil to create a glossy restaurant-quality sauce without needing cream.",
    ingredients: [
      { name: "pasta", amount: 200, unit: "g", original: "200g spaghetti or linguine" },
      { name: "garlic", amount: 5, unit: "cloves", original: "5 garlic cloves, thinly sliced" },
      { name: "olive oil", amount: 4, unit: "tbsp", original: "4 tbsp extra virgin olive oil" },
      { name: "red pepper flakes", amount: 1, unit: "tsp", original: "1 tsp red pepper chili flakes" },
      { name: "parsley", amount: 0.25, unit: "cup", original: "1/4 cup fresh parsley, chopped" },
      { name: "cheese", amount: 0.25, unit: "cup", original: "1/4 cup grated Parmesan or Pecorino cheese (optional)" }
    ],
    instructions: [
      "Bring a large pot of salted water to a rolling boil. Add spaghetti and cook until 1 minute shy of al dente.",
      "While pasta cooks, heat olive oil in a wide skillet over medium-low heat. Add thinly sliced garlic and chili flakes.",
      "Gently cook garlic for 2-3 minutes until pale golden and fragrant (do not burn!).",
      "Using tongs, transfer cooked pasta directly into the skillet. Splash in 1/2 cup of reserved starchy pasta water.",
      "Toss vigorously over medium heat until a glossy, velvety sauce coats the pasta.",
      "Remove from heat, fold in fresh chopped parsley and grated cheese. Serve immediately."
    ]
  },
  {
    id: "rec-02",
    title: "Creamy Garlic Parmesan Tuscan Chicken",
    category: "Dinner",
    cuisine: "Italian-American",
    mealType: "Dinner",
    difficulty: "Medium",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 520,
    macros: { protein: "42g", carbs: "8g", fat: "34g" },
    diet: ["Low-Carb", "High-Protein", "Gluten-Free"],
    rating: 4.95,
    reviewsCount: 218,
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80",
    description: "Tender pan-seared chicken breasts enveloped in a rich garlic cream sauce bursting with sweet tomatoes, garlic, and tender baby spinach.",
    wasteReductionTip: "Have wilting spinach or cherry tomatoes? Sauté them right into the sauce to instantly revive their flavor.",
    ingredients: [
      { name: "chicken breast", amount: 2, unit: "large breasts", original: "2 large chicken breasts, halved horizontally into cutlets" },
      { name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic, minced" },
      { name: "spinach", amount: 2, unit: "cups", original: "2 cups fresh baby spinach" },
      { name: "tomato", amount: 1, unit: "cup", original: "1 cup cherry tomatoes or sun-dried tomatoes, diced" },
      { name: "heavy cream", amount: 0.75, unit: "cup", original: "3/4 cup heavy cream (or Greek yogurt + milk)" },
      { name: "cheese", amount: 0.5, unit: "cup", original: "1/2 cup grated Parmesan cheese" },
      { name: "olive oil", amount: 2, unit: "tbsp", original: "2 tbsp olive oil" },
      { name: "butter", amount: 1, unit: "tbsp", original: "1 tbsp butter" }
    ],
    instructions: [
      "Season chicken cutlets generously with salt, black pepper, and Italian herbs.",
      "Heat olive oil and butter in a large skillet over medium-high heat. Sear chicken for 4-5 minutes per side until golden brown and cooked through (165°F). Remove and set aside on a warm plate.",
      "In the same skillet, reduce heat to medium and sauté minced garlic and tomatoes for 2 minutes until fragrant.",
      "Pour in heavy cream and chicken broth (if available). Bring to a gentle simmer for 3 minutes until slightly thickened.",
      "Stir in grated Parmesan and baby spinach until the spinach wilts and cheese dissolves smoothly.",
      "Nestle the cooked chicken back into the skillet, spoon sauce generously over the top, and serve warm."
    ]
  },
  {
    id: "rec-03",
    title: "15-Minute Tomato Basil Butter Pasta",
    category: "Lunch",
    cuisine: "Italian",
    mealType: "Lunch",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 380,
    macros: { protein: "10g", carbs: "56g", fat: "12g" },
    diet: ["Vegetarian"],
    rating: 4.8,
    reviewsCount: 95,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281728?auto=format&fit=crop&w=800&q=80",
    description: "Burst sweet tomatoes simmered in butter and garlic until jammy, tossed with penne and fragrant fresh basil leaves.",
    wasteReductionTip: "Overripe, slightly wrinkly tomatoes are the sweetest and release the most rich tomato juices for this quick sauce.",
    ingredients: [
      { name: "pasta", amount: 200, unit: "g", original: "200g penne or fusilli pasta" },
      { name: "tomato", amount: 2, unit: "cups", original: "2 cups ripe tomatoes or cherry tomatoes, chopped" },
      { name: "butter", amount: 2, unit: "tbsp", original: "2 tbsp butter" },
      { name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic, minced" },
      { name: "basil", amount: 0.25, unit: "cup", original: "1/4 cup fresh basil or 1 tsp dried basil" },
      { name: "cheese", amount: 0.25, unit: "cup", original: "1/4 cup grated cheese" }
    ],
    instructions: [
      "Cook pasta in salted boiling water until al dente. Reserve 1/4 cup cooking liquid before draining.",
      "Melt butter in a skillet over medium heat. Add minced garlic and cook for 1 minute.",
      "Add chopped tomatoes with a pinch of salt. Cook for 5-7 minutes, pressing tomatoes with a wooden spoon until they burst into a rich saucy glaze.",
      "Add drained pasta and 2 tablespoons of starchy pasta water to the pan.",
      "Toss everything together until pasta is evenly coated in the sweet butter sauce. Top with fresh torn basil and cheese."
    ]
  },
  {
    id: "rec-04",
    title: "Crispy Golden Vegetable Fried Rice",
    category: "Dinner",
    cuisine: "Asian",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 10,
    servings: 3,
    calories: 360,
    macros: { protein: "11g", carbs: "54g", fat: "10g" },
    diet: ["Vegetarian"],
    rating: 4.85,
    reviewsCount: 164,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
    description: "The ultimate zero-waste refrigerator cleanup meal. Day-old rice stir-fried on high heat with eggs, crisp veggies, and aromatic soy-garlic sauce.",
    wasteReductionTip: "Day-old cold leftover rice is ideal because it dehydrates in the fridge, preventing mushy fried rice.",
    ingredients: [
      { name: "rice", amount: 3, unit: "cups", original: "3 cups chilled cooked leftover rice" },
      { name: "egg", amount: 2, unit: "large", original: "2 eggs, beaten" },
      { name: "onion", amount: 1, unit: "medium", original: "1 medium onion or green onions, finely chopped" },
      { name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic, minced" },
      { name: "carrot", amount: 1, unit: "medium", original: "1 carrot, finely diced" },
      { name: "bell pepper", amount: 1, unit: "half", original: "1/2 bell pepper or peas/corn, diced" },
      { name: "soy sauce", amount: 2.5, unit: "tbsp", original: "2.5 tbsp soy sauce" },
      { name: "olive oil", amount: 2, unit: "tbsp", original: "2 tbsp cooking oil" }
    ],
    instructions: [
      "Heat 1 tablespoon oil in a large wok or wide non-stick skillet over high heat.",
      "Pour in beaten eggs, scramble softly for 45 seconds, then remove eggs to a plate.",
      "Add remaining oil to the pan. Add diced onions, garlic, carrots, and bell peppers. Stir fry vigorously for 3 minutes until tender-crisp.",
      "Turn heat to maximum. Add cold cooked rice, breaking up clumps with your spatula.",
      "Drizzle soy sauce around the perimeter of the pan so it sizzles into the rice. Toss continuously for 3 minutes until grains are toasted.",
      "Fold the scrambled eggs back in, season with black pepper, and serve hot."
    ]
  },
  {
    id: "rec-05",
    title: "Authentic Shakshuka with Poached Eggs",
    category: "Breakfast",
    cuisine: "Middle Eastern",
    mealType: "Breakfast",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 310,
    macros: { protein: "16g", carbs: "18g", fat: "19g" },
    diet: ["Vegetarian", "Gluten-Free", "Low-Carb"],
    rating: 4.92,
    reviewsCount: 187,
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=800&q=80",
    description: "Eggs gently poached in a spiced, bubbling sauce of crushed tomatoes, bell peppers, onions, cumin, and garlic. Perfect with crusty bread.",
    wasteReductionTip: "Any soft bell peppers or stray cans of diced tomatoes can be transformed into this fragrant brunch centerpiece.",
    ingredients: [
      { name: "egg", amount: 4, unit: "large", original: "4 large eggs" },
      { name: "tomato", amount: 2, unit: "cups", original: "2 cups crushed tomatoes or canned diced tomatoes" },
      { name: "bell pepper", amount: 1, unit: "large", original: "1 red or yellow bell pepper, chopped" },
      { name: "onion", amount: 1, unit: "medium", original: "1 onion, diced" },
      { name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic, minced" },
      { name: "olive oil", amount: 2, unit: "tbsp", original: "2 tbsp olive oil" },
      { name: "cheese", amount: 0.25, unit: "cup", original: "1/4 cup feta cheese or goat cheese (optional)" }
    ],
    instructions: [
      "Heat olive oil in a deep skillet over medium heat. Sauté diced onion and bell pepper for 5 minutes until soft and caramelized.",
      "Add minced garlic, 1 tsp cumin, 1 tsp paprika, and salt. Cook for 1 minute until fragrant.",
      "Pour in crushed tomatoes, bring to a simmer, and let bubble on medium-low for 8 minutes until thickened.",
      "Use the back of a spoon to make 4 small wells in the sauce. Gently crack an egg into each well.",
      "Cover skillet with a lid and cook on low heat for 5-7 minutes until egg whites are set and yolks remain runny.",
      "Garnish with crumbled cheese and fresh herbs. Serve warm directly from skillet with warm toasted bread."
    ]
  },
  {
    id: "rec-06",
    title: "Loaded Black Bean & Cheese Quesadillas",
    category: "Lunch",
    cuisine: "Mexican",
    mealType: "Lunch",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 440,
    macros: { protein: "18g", carbs: "48g", fat: "20g" },
    diet: ["Vegetarian"],
    rating: 4.78,
    reviewsCount: 110,
    image: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=800&q=80",
    description: "Golden, crisp tortillas filled with melted cheese, hearty black beans, sautéed onions, sweet corn, and a zesty squeeze of lime.",
    wasteReductionTip: "Use leftover canned beans, stray cheese blocks, or leftover taco fillings for a fast zero-waste lunch.",
    ingredients: [
      { name: "bread", amount: 4, unit: "tortillas", original: "4 flour or corn tortillas" },
      { name: "cheese", amount: 1.5, unit: "cups", original: "1.5 cups shredded cheddar, Monterey Jack, or mozzarella" },
      { name: "black beans", amount: 1, unit: "cup", original: "1 cup canned black beans, rinsed and drained" },
      { name: "onion", amount: 0.5, unit: "medium", original: "1/2 onion, finely diced" },
      { name: "bell pepper", amount: 0.5, unit: "medium", original: "1/2 bell pepper, diced" },
      { name: "butter", amount: 1, unit: "tbsp", original: "1 tbsp butter or oil for pan frying" }
    ],
    instructions: [
      "In a small bowl, lightly mash 1/2 of the black beans with a fork (helps bind the filling), leaving the other half whole. Mix in diced onion, bell pepper, cumin, and salt.",
      "Heat a skillet over medium heat with a tiny dab of butter or olive oil.",
      "Lay one tortilla flat. Scatter shredded cheese evenly over half the tortilla, spoon bean mixture on top, and add another pinch of cheese.",
      "Fold tortilla over into a half-moon. Cook for 2-3 minutes per side until golden brown and crisp with cheese bubbling out.",
      "Slice into triangles and serve immediately with salsa or sour cream."
    ]
  },
  {
    id: "rec-07",
    title: "Cheesy Potato & Onion Spanish Frittata",
    category: "Breakfast",
    cuisine: "Spanish",
    mealType: "Breakfast",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 290,
    macros: { protein: "14g", carbs: "22g", fat: "16g" },
    diet: ["Vegetarian", "Gluten-Free"],
    rating: 4.88,
    reviewsCount: 135,
    image: "https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=800&q=80",
    description: "A rustic Spanish omelet packed with tender golden sliced potatoes, sweet caramelized onions, whisked eggs, and gooey melted cheese.",
    wasteReductionTip: "Leftover boiled or baked potatoes work even faster! Just slice and brown them directly in the skillet.",
    ingredients: [
      { name: "potato", amount: 2, unit: "medium", original: "2 medium potatoes, peeled and thinly sliced" },
      { name: "egg", amount: 5, unit: "large", original: "5 large eggs, whisked" },
      { name: "onion", amount: 1, unit: "medium", original: "1 large yellow onion, thinly sliced" },
      { name: "cheese", amount: 0.75, unit: "cup", original: "3/4 cup grated cheese" },
      { name: "olive oil", amount: 3, unit: "tbsp", original: "3 tbsp olive oil" }
    ],
    instructions: [
      "Heat olive oil in an oven-safe 10-inch skillet over medium heat. Add sliced potatoes and onions with salt and pepper.",
      "Cook gently, stirring occasionally, for 10-12 minutes until potatoes are fork-tender and onions are caramelized.",
      "Whisk eggs with a pinch of salt and stir in half the cheese.",
      "Pour whisked eggs evenly over the potatoes and onions in the pan. Reduce heat to low.",
      "Cook for 6-8 minutes until edges set and center is almost firm. Sprinkle remaining cheese on top.",
      "Broil in oven or invert onto a plate to flip for 2 minutes until golden on top. Slice into wedges."
    ]
  },
  {
    id: "rec-08",
    title: "Creamy Garlic Butter Mushroom Risotto",
    category: "Dinner",
    cuisine: "Italian",
    mealType: "Dinner",
    difficulty: "Medium",
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    calories: 460,
    macros: { protein: "11g", carbs: "64g", fat: "18g" },
    diet: ["Vegetarian", "Gluten-Free"],
    rating: 4.91,
    reviewsCount: 173,
    image: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=800&q=80",
    description: "Luxurious, velvety arborio rice gently simmered in savory broth with deeply browned garlic butter mushrooms and aged cheese.",
    wasteReductionTip: "Mushroom stems are packed with umami. Don't discard them; chop them finely and sauté together with the caps.",
    ingredients: [
      { name: "rice", amount: 1.5, unit: "cups", original: "1.5 cups Arborio rice (or short-grain white rice)" },
      { name: "mushroom", amount: 250, unit: "g", original: "250g mushrooms (cremini or button), sliced" },
      { name: "onion", amount: 1, unit: "small", original: "1 small onion or shallot, finely minced" },
      { name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic, minced" },
      { name: "butter", amount: 3, unit: "tbsp", original: "3 tbsp butter, divided" },
      { name: "cheese", amount: 0.5, unit: "cup", original: "1/2 cup grated parmesan cheese" },
      { name: "olive oil", amount: 1, unit: "tbsp", original: "1 tbsp olive oil" }
    ],
    instructions: [
      "In a wide skillet, heat 1 tbsp butter and 1 tbsp olive oil over medium-high heat. Add sliced mushrooms and cook undisturbed for 4 minutes until deeply browned. Season with salt, add half the minced garlic, toss 1 minute, and set aside.",
      "In the same pan, melt another tbsp butter over medium heat. Sauté minced onion until translucent (3 min).",
      "Add dry rice to the pan and toast for 2 minutes until edges look translucent.",
      "Add warm broth (or salted water) 1 ladle at a time, stirring frequently until liquid is absorbed before adding the next ladle. Repeat for 18-20 minutes until rice is creamy and tender.",
      "Fold in sautéed mushrooms, remaining butter, and grated cheese. Stir vigorously until creamy, cover for 2 minutes, and serve."
    ]
  },
  {
    id: "rec-09",
    title: "Mediterranean Chickpea & Avocado Power Salad",
    category: "Lunch",
    cuisine: "Mediterranean",
    mealType: "Lunch",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    calories: 390,
    macros: { protein: "14g", carbs: "42g", fat: "21g" },
    diet: ["Vegetarian", "Vegan", "Gluten-Free", "High-Protein"],
    rating: 4.84,
    reviewsCount: 156,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    description: "Crisp, refreshing, and protein-packed salad loaded with nutty chickpeas, creamy avocado chunks, juicy tomatoes, cucumber, and lemon dressing.",
    wasteReductionTip: "Zero cooking required! Save the chickpea canning liquid (aquafaba) to whip as an egg-free mayonnaise or dessert foam.",
    ingredients: [
      { name: "chickpeas", amount: 1.5, unit: "cups", original: "1 can (15 oz) chickpeas, rinsed and drained" },
      { name: "avocado", amount: 1, unit: "medium", original: "1 ripe avocado, diced" },
      { name: "tomato", amount: 1, unit: "cup", original: "1 cup cherry tomatoes, halved" },
      { name: "onion", amount: 0.25, unit: "cup", original: "1/4 red onion, thinly sliced" },
      { name: "lemon", amount: 1, unit: "whole", original: "1 lemon, juiced" },
      { name: "olive oil", amount: 2, unit: "tbsp", original: "2 tbsp extra virgin olive oil" },
      { name: "spinach", amount: 2, unit: "cups", original: "2 cups baby spinach or mixed greens" }
    ],
    instructions: [
      "In a large salad bowl, whisk olive oil, fresh lemon juice, salt, black pepper, and dried oregano together.",
      "Add drained chickpeas, halved cherry tomatoes, and thinly sliced red onion. Toss to marinate for 5 minutes.",
      "Gently fold in fresh baby spinach leaves and diced avocado so the avocado stays intact.",
      "Taste and adjust seasoning with extra lemon juice or black pepper. Serve chilled or at room temperature."
    ]
  },
  {
    id: "rec-10",
    title: "Golden Honey Garlic Glazed Salmon",
    category: "Dinner",
    cuisine: "Fusion",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 480,
    macros: { protein: "38g", carbs: "18g", fat: "28g" },
    diet: ["High-Protein", "Gluten-Free"],
    rating: 4.96,
    reviewsCount: 220,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80",
    description: "Flaky pan-seared salmon fillets coated in an irresistible caramelized sweet-savory glaze of honey, soy sauce, garlic, and fresh lemon.",
    wasteReductionTip: "Crispy salmon skin holds tons of omega-3 nutrients! Sear skin-side down first for unmatched crunch.",
    ingredients: [
      { name: "salmon", amount: 2, unit: "fillets", original: "2 fresh salmon fillets (approx 6 oz each)" },
      { name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic, minced" },
      { name: "honey", amount: 3, unit: "tbsp", original: "3 tbsp honey (or maple syrup)" },
      { name: "soy sauce", amount: 2, unit: "tbsp", original: "2 tbsp soy sauce or tamari" },
      { name: "lemon", amount: 0.5, unit: "whole", original: "1/2 lemon, juiced" },
      { name: "butter", amount: 1, unit: "tbsp", original: "1 tbsp butter" },
      { name: "olive oil", amount: 1, unit: "tbsp", original: "1 tbsp olive oil" }
    ],
    instructions: [
      "Pat salmon dry with paper towels; season both sides with salt and cracked black pepper.",
      "In a small ramekin, whisk together honey, soy sauce, lemon juice, and minced garlic.",
      "Heat olive oil and butter in a skillet over medium-high heat. Place salmon fillets skin side down (or flesh down if skinless) and cook undisturbed for 4 minutes until golden and crisp.",
      "Flip salmon carefully. Pour honey-garlic sauce into the pan around the fish.",
      "Simmer sauce for 3-4 minutes, spooning the bubbling glaze repeatedly over the salmon until sticky, thick, and salmon is cooked through.",
      "Garnish with lemon slices and serve over rice or steamed greens."
    ]
  },
  {
    id: "rec-11",
    title: "Garlic Butter Shrimp Scampi",
    category: "Dinner",
    cuisine: "Italian-American",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    calories: 360,
    macros: { protein: "28g", carbs: "6g", fat: "24g" },
    diet: ["Low-Carb", "High-Protein", "Gluten-Free"],
    rating: 4.89,
    reviewsCount: 168,
    image: "https://images.unsplash.com/photo-1559742811-82286364ceaf?auto=format&fit=crop&w=800&q=80",
    description: "Plump, juicy shrimp seared in melted butter, extra virgin olive oil, minced garlic, a splash of lemon, and finished with fresh parsley.",
    wasteReductionTip: "Shrimp shells can be simmered in water with onion peel to make a fragrant homemade seafood stock.",
    ingredients: [
      { name: "shrimp", amount: 300, unit: "g", original: "300g raw shrimp, peeled and deveined" },
      { name: "garlic", amount: 5, unit: "cloves", original: "5 cloves garlic, minced" },
      { name: "butter", amount: 3, unit: "tbsp", original: "3 tbsp unsalted butter" },
      { name: "olive oil", amount: 1, unit: "tbsp", original: "1 tbsp olive oil" },
      { name: "lemon", amount: 1, unit: "whole", original: "1 lemon, zested and juiced" },
      { name: "red pepper flakes", amount: 0.5, unit: "tsp", original: "1/2 tsp red pepper flakes" }
    ],
    instructions: [
      "Pat shrimp thoroughly dry with paper towels; season lightly with salt and black pepper.",
      "Heat olive oil and 1 tablespoon butter in a wide skillet over medium heat.",
      "Add minced garlic and red pepper flakes. Cook for 1 minute until fragrant without browning.",
      "Add shrimp in a single layer. Cook for 2 minutes on the first side until turning pink, then flip and cook 1-2 minutes on the second side.",
      "Remove pan from heat. Swirl in remaining 2 tablespoons cold butter, fresh lemon juice, and zest until an emulsified sauce forms.",
      "Serve over pasta, rice, or with warm sourdough to dip into the buttery sauce."
    ]
  },
  {
    id: "rec-12",
    title: "Fluffy Banana Oat Pancakes",
    category: "Breakfast",
    cuisine: "American",
    mealType: "Breakfast",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 320,
    macros: { protein: "12g", carbs: "52g", fat: "7g" },
    diet: ["Vegetarian", "Gluten-Free"],
    rating: 4.87,
    reviewsCount: 140,
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=800&q=80",
    description: "Naturally sweet, golden blender pancakes made without refined flour or sugar! Made with ripe bananas, rolled oats, eggs, and cinnamon.",
    wasteReductionTip: "The brown spotted bananas on your counter produce the sweetest, fluffiest pancakes.",
    ingredients: [
      { name: "banana", amount: 2, unit: "medium", original: "2 ripe bananas, peeled" },
      { name: "oats", amount: 1, unit: "cup", original: "1 cup rolled oats (blended into oat flour)" },
      { name: "egg", amount: 2, unit: "large", original: "2 large eggs" },
      { name: "milk", amount: 0.25, unit: "cup", original: "1/4 cup milk or almond milk" },
      { name: "butter", amount: 1, unit: "tbsp", original: "1 tbsp butter or oil for greasing skillet" },
      { name: "honey", amount: 1, unit: "tbsp", original: "1 tbsp honey or maple syrup for serving" }
    ],
    instructions: [
      "Add rolled oats, bananas, eggs, milk, 1/2 tsp baking powder, and a pinch of cinnamon into a blender. Blend on high for 30 seconds until a smooth batter forms.",
      "Let the batter sit for 3 minutes to thicken slightly.",
      "Heat a non-stick skillet or griddle over medium-low heat and grease with a little butter.",
      "Pour 1/4 cup batter for each pancake. Cook for 2-3 minutes until bubbles form on the surface and edges look matte.",
      "Carefully flip and cook for 1-2 minutes until golden brown on the underside.",
      "Stack high and drizzle with honey, maple syrup, or peanut butter."
    ]
  },
  {
    id: "rec-13",
    title: "Golden Turmeric Crispy Tofu Stir-Fry",
    category: "Dinner",
    cuisine: "Asian",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    calories: 340,
    macros: { protein: "22g", carbs: "16g", fat: "22g" },
    diet: ["Vegetarian", "Vegan", "Gluten-Free", "High-Protein"],
    rating: 4.82,
    reviewsCount: 98,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    description: "Extra crispy cubed tofu sautéed with broccoli florets, bell peppers, garlic, ginger, and savory soy-sesame glaze.",
    wasteReductionTip: "Broccoli stems can be peeled and sliced into crunchy coins for stir-fries rather than thrown away.",
    ingredients: [
      { name: "tofu", amount: 350, unit: "g", original: "350g extra-firm tofu, pressed and cubed" },
      { name: "broccoli", amount: 2, unit: "cups", original: "2 cups broccoli florets" },
      { name: "bell pepper", amount: 1, unit: "medium", original: "1 bell pepper, sliced" },
      { name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic, minced" },
      { name: "soy sauce", amount: 2, unit: "tbsp", original: "2 tbsp soy sauce or tamari" },
      { name: "olive oil", amount: 2, unit: "tbsp", original: "2 tbsp cooking oil" }
    ],
    instructions: [
      "Press tofu with a kitchen towel for 10 minutes to remove excess moisture. Cut into 3/4-inch cubes and toss with 1 tbsp cornstarch or flour for extra crispness.",
      "Heat 1.5 tbsp oil in a wide skillet over high heat. Add tofu cubes in a single layer and sear for 6-8 minutes, turning occasionally until golden and crunchy on all sides. Transfer to a plate.",
      "Add remaining oil to the pan. Sauté garlic, broccoli, and bell pepper for 3-4 minutes with 2 tbsp water to steam-fry.",
      "Return crispy tofu to the skillet. Drizzle with soy sauce and toss everything for 1-2 minutes until glossy.",
      "Serve warm over jasmine rice or quinoa."
    ]
  },
  {
    id: "rec-14",
    title: "Classic Margherita French Bread Pizza",
    category: "Lunch",
    cuisine: "Italian",
    mealType: "Lunch",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 12,
    servings: 3,
    calories: 380,
    macros: { protein: "16g", carbs: "44g", fat: "16g" },
    diet: ["Vegetarian"],
    rating: 4.86,
    reviewsCount: 129,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80",
    description: "Crispy-on-the-bottom, soft-in-the-middle French bread halves slathered with garlicky tomato sauce, melted mozzarella, sliced tomatoes, and basil.",
    wasteReductionTip: "Turn yesterday's stale baguette or bread slices into a gourmet crispy pizza base instead of throwing it out.",
    ingredients: [
      { name: "bread", amount: 1, unit: "loaf", original: "1 French bread baguette or bread slices" },
      { name: "cheese", amount: 2, unit: "cups", original: "2 cups shredded mozzarella cheese" },
      { name: "tomato", amount: 1, unit: "cup", original: "1 cup crushed tomato sauce + 1 fresh tomato, sliced" },
      { name: "garlic", amount: 2, unit: "cloves", original: "2 cloves garlic, minced" },
      { name: "olive oil", amount: 2, unit: "tbsp", original: "2 tbsp olive oil" },
      { name: "basil", amount: 0.25, unit: "cup", original: "Fresh basil leaves" }
    ],
    instructions: [
      "Preheat oven to 400°F (200°C) and line a baking sheet with parchment paper.",
      "Cut French bread lengthwise in half. Brush cut sides with olive oil mixed with minced garlic.",
      "Bake bread naked for 4 minutes to toast lightly (prevents sogginess!).",
      "Spread tomato sauce evenly across bread. Layer with shredded mozzarella and sliced ripe tomatoes.",
      "Return to oven and bake for 8-10 minutes until cheese is completely melted and bubbly with golden edges.",
      "Top with fresh basil leaves, slice into portable pieces, and enjoy."
    ]
  },
  {
    id: "rec-15",
    title: "Comforting Cream of Broccoli & Cheddar Soup",
    category: "Dinner",
    cuisine: "American",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 340,
    macros: { protein: "14g", carbs: "18g", fat: "24g" },
    diet: ["Vegetarian", "Gluten-Free"],
    rating: 4.89,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    description: "A velvety, warm bowl of broccoli simmered with onions, garlic, and vegetable stock, blended silky smooth with sharp cheddar cheese.",
    wasteReductionTip: "Broccoli stalks are completely edible! Peel the fibrous outer layer and dice the tender inner core right into the soup.",
    ingredients: [
      { name: "broccoli", amount: 4, unit: "cups", original: "4 cups broccoli florets and stems, chopped" },
      { name: "cheese", amount: 1.5, unit: "cups", original: "1.5 cups sharp cheddar cheese, shredded" },
      { name: "onion", amount: 1, unit: "medium", original: "1 medium onion, diced" },
      { name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic, minced" },
      { name: "milk", amount: 1.5, unit: "cups", original: "1.5 cups milk or heavy cream" },
      { name: "butter", amount: 2, unit: "tbsp", original: "2 tbsp butter" },
      { name: "potato", amount: 1, unit: "medium", original: "1 medium potato, peeled and diced (for natural creamy thickening)" }
    ],
    instructions: [
      "Melt butter in a large soup pot over medium heat. Sauté diced onion and garlic for 3 minutes until fragrant.",
      "Add diced potato and chopped broccoli. Pour in 2 cups of water or vegetable stock. Bring to a boil.",
      "Reduce heat, cover, and simmer for 12-15 minutes until potatoes and broccoli are fork-tender.",
      "Use an immersion blender (or stand blender) to puree the soup until smooth and creamy.",
      "Stir in milk and reduce heat to low. Gradually fold in shredded cheddar cheese until melted and velvety.",
      "Season with salt, pepper, and nutmeg. Serve with crusty bread."
    ]
  },
  {
    id: "rec-16",
    title: "Smashed Avocado & Soft Jammy Egg Toast",
    category: "Breakfast",
    cuisine: "Modern Cafe",
    mealType: "Breakfast",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 6,
    servings: 1,
    calories: 330,
    macros: { protein: "14g", carbs: "26g", fat: "19g" },
    diet: ["Vegetarian"],
    rating: 4.93,
    reviewsCount: 195,
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    description: "Thick golden toasted sourdough piled high with creamy lemon-dressed smashed avocado, chili flakes, and a 6-minute jammy boiled egg.",
    wasteReductionTip: "Have half an avocado left? Squeeze fresh lemon juice over the cut surface and store with the pit in an airtight container to prevent browning.",
    ingredients: [
      { name: "bread", amount: 2, unit: "slices", original: "2 thick slices sourdough or multigrain bread" },
      { name: "avocado", amount: 1, unit: "medium", original: "1 ripe avocado" },
      { name: "egg", amount: 2, unit: "large", original: "2 large eggs" },
      { name: "lemon", amount: 0.5, unit: "whole", original: "1/2 lemon, juiced" },
      { name: "olive oil", amount: 1, unit: "tsp", original: "1 tsp extra virgin olive oil" },
      { name: "red pepper flakes", amount: 0.5, unit: "tsp", original: "Pinch of red pepper flakes and flaky sea salt" }
    ],
    instructions: [
      "Bring a small pot of water to a gentle boil. Lower eggs in carefully with a spoon and boil for exactly 6.5 minutes for jammy yolks.",
      "Immediately plunge eggs into an ice bath for 3 minutes, then peel gently.",
      "In a bowl, mash avocado flesh with lemon juice, olive oil, salt, and pepper.",
      "Toast bread slices until golden brown and sturdy.",
      "Spread smashed avocado generously over warm toast. Slice jammy eggs in half and place on top.",
      "Sprinkle with chili flakes, flaky salt, and serve."
    ]
  },
  {
    id: "rec-17",
    title: "Hearty Chickpea & Spinach Stew",
    category: "Dinner",
    cuisine: "Mediterranean",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 280,
    macros: { protein: "14g", carbs: "44g", fat: "6g" },
    diet: ["Vegetarian", "Vegan", "Gluten-Free", "High-Protein"],
    rating: 4.81,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80",
    description: "A nourishing, fiber-rich stew of protein-packed chickpeas, tender carrots, onions, tomatoes, and wilted baby spinach, infused with cumin and lemon.",
    wasteReductionTip: "Chickpeas don't require pre-soaking if canned and absorb leftover stray vegetable bits easily.",
    ingredients: [
      { name: "chickpeas", amount: 2, unit: "cups", original: "2 cans chickpeas, drained and rinsed" },
      { name: "spinach", amount: 2, unit: "cups", original: "2 cups fresh baby spinach" },
      { name: "carrot", amount: 2, unit: "medium", original: "2 carrots, diced" },
      { name: "onion", amount: 1, unit: "medium", original: "1 onion, chopped" },
      { name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic, minced" },
      { name: "tomato", amount: 1, unit: "cup", original: "1 cup diced tomatoes" },
      { name: "lemon", amount: 1, unit: "whole", original: "1 lemon, juiced" }
    ],
    instructions: [
      "Heat 1 tbsp olive oil in a deep pot over medium heat. Sauté diced onion, garlic, and carrots for 5 minutes.",
      "Add cumin, coriander, and diced tomatoes; cook for 2 minutes.",
      "Add drained chickpeas along with 2 cups of vegetable stock or water.",
      "Bring to a simmer, cover with lid, and cook for 15 minutes to allow flavors to meld.",
      "Stir in baby spinach until wilted. Remove from heat and stir in fresh lemon juice.",
      "Ladle into bowls and serve with toasted bread or rice."
    ]
  },
  {
    id: "rec-18",
    title: "10-Minute Garlic Chili Egg Fried Noodles",
    category: "Lunch",
    cuisine: "Street Food",
    mealType: "Lunch",
    difficulty: "Easy",
    prepTime: 3,
    cookTime: 7,
    servings: 2,
    calories: 410,
    macros: { protein: "15g", carbs: "58g", fat: "14g" },
    diet: ["Vegetarian"],
    rating: 4.88,
    reviewsCount: 153,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    description: "Chewy noodles tossed in a sizzling garlic chili oil sauce, scrambled eggs, scallions, and savory soy sauce in under 10 minutes.",
    wasteReductionTip: "Any noodles in your pantry work: instant ramen blocks, spaghetti, or soba noodles.",
    ingredients: [
      { name: "pasta", amount: 200, unit: "g", original: "200g ramen, egg noodles, or spaghetti" },
      { name: "egg", amount: 2, unit: "large", original: "2 large eggs, whisked" },
      { name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic, finely minced" },
      { name: "soy sauce", amount: 2.5, unit: "tbsp", original: "2.5 tbsp soy sauce" },
      { name: "onion", amount: 0.5, unit: "cup", original: "1/2 cup scallions or sliced onion" },
      { name: "olive oil", amount: 2, unit: "tbsp", original: "2 tbsp cooking oil" }
    ],
    instructions: [
      "Boil noodles according to package directions until tender; drain and rinse with cold water.",
      "Heat 1 tbsp oil in a skillet over high heat. Pour in whisked eggs, scramble soft for 40 seconds, then set aside.",
      "Add remaining oil to skillet. Sauté minced garlic and chili flakes for 30 seconds until aromatic.",
      "Toss in cooked noodles, soy sauce, and 1 tsp sugar. Stir-fry vigorously on high heat for 2 minutes.",
      "Toss the scrambled eggs and sliced scallions back in.",
      "Serve sizzling hot with a squeeze of lime."
    ]
  },
  {
    id: "rec-19",
    title: "Greek Lemon Herb Roasted Potatoes",
    category: "Side Dish",
    cuisine: "Greek",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    calories: 220,
    macros: { protein: "4g", carbs: "38g", fat: "7g" },
    diet: ["Vegetarian", "Vegan", "Gluten-Free"],
    rating: 4.94,
    reviewsCount: 165,
    image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80",
    description: "Crispy edged wedges on the outside, meltingly tender on the inside, roasted in a zesty emulsion of lemon juice, olive oil, garlic, and oregano.",
    wasteReductionTip: "Keep the potato skins on! They deliver extra crispiness, texture, and dietary fiber.",
    ingredients: [
      { name: "potato", amount: 4, unit: "large", original: "4 large russet or Yukon gold potatoes, cut into wedges" },
      { name: "lemon", amount: 2, unit: "whole", original: "2 whole lemons, juiced" },
      { name: "olive oil", amount: 3, unit: "tbsp", original: "3 tbsp extra virgin olive oil" },
      { name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic, minced" },
      { name: "butter", amount: 1, unit: "tbsp", original: "1 tbsp melted butter" }
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "Cut washed potatoes into thick wedges and place in a large roasting pan.",
      "In a bowl, whisk olive oil, lemon juice, minced garlic, 1 tbsp dried oregano, salt, pepper, and 1/2 cup water.",
      "Pour mixture over potatoes and toss to coat evenly.",
      "Roast for 35-40 minutes, flipping once halfway through, until liquid has reduced and potato edges are deeply browned and crispy.",
      "Garnish with fresh parsley and serve hot."
    ]
  },
  {
    id: "rec-20",
    title: "Cheesy Stuffed Spinach & Garlic Omelet",
    category: "Breakfast",
    cuisine: "French",
    mealType: "Breakfast",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    calories: 280,
    macros: { protein: "18g", carbs: "3g", fat: "22g" },
    diet: ["Vegetarian", "Low-Carb", "Gluten-Free", "High-Protein"],
    rating: 4.87,
    reviewsCount: 104,
    image: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80",
    description: "Silky French-style folded eggs loaded with sautéed baby spinach, garlic butter, and gooey melted cheese.",
    wasteReductionTip: "Wilted greens can be cooked in seconds without losing any nutrition or flavor.",
    ingredients: [
      { name: "egg", amount: 3, unit: "large", original: "3 large eggs" },
      { name: "spinach", amount: 1.5, unit: "cups", original: "1.5 cups fresh baby spinach" },
      { name: "cheese", amount: 0.33, unit: "cup", original: "1/3 cup grated cheddar, goat cheese, or mozzarella" },
      { name: "butter", amount: 1, unit: "tbsp", original: "1 tbsp butter" },
      { name: "garlic", amount: 1, unit: "clove", original: "1 clove garlic, minced" }
    ],
    instructions: [
      "Melt half the butter in an 8-inch nonstick skillet over medium heat. Sauté garlic and spinach for 1 minute until wilted; transfer to a plate.",
      "Whisk eggs with 1 tablespoon water, salt, and black pepper until completely uniform.",
      "Melt remaining butter in the skillet over medium-low heat. Pour in eggs.",
      "Gently pull cooked edges toward the center with a spatula, tilting pan to let uncooked egg flow to edges.",
      "When the surface is soft and barely set, arrange sautéed spinach and cheese across one half of the omelet.",
      "Fold the other half over the filling, slide onto a warm plate, and serve."
    ]
  },
  {
    id: "rec-21",
    title: "One-Pot Creamy Macaroni & Cheese",
    category: "Dinner",
    cuisine: "Comfort Food",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 12,
    servings: 3,
    calories: 510,
    macros: { protein: "19g", carbs: "52g", fat: "26g" },
    diet: ["Vegetarian"],
    rating: 4.91,
    reviewsCount: 230,
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    description: "Ultra-velvety, decadent stovetop mac and cheese cooked in a single pot. No complicated roux needed!",
    wasteReductionTip: "Combine end pieces of random cheeses (cheddar, gouda, mozzarella, parmesan) for the ultimate custom blend.",
    ingredients: [
      { name: "pasta", amount: 250, unit: "g", original: "250g elbow macaroni pasta" },
      { name: "milk", amount: 2, unit: "cups", original: "2 cups whole milk" },
      { name: "cheese", amount: 2, unit: "cups", original: "2 cups shredded sharp cheddar and mozzarella" },
      { name: "butter", amount: 2, unit: "tbsp", original: "2 tbsp butter" },
      { name: "garlic", amount: 0.5, unit: "tsp", original: "1/2 tsp garlic powder & pinch of salt" }
    ],
    instructions: [
      "In a medium pot, combine macaroni pasta, milk, 1 cup water, and 1/2 tsp salt.",
      "Bring to a gentle boil over medium heat, stirring continuously so pasta doesn't stick to the bottom.",
      "Simmer for 8-9 minutes until pasta is tender and liquid is absorbed into a thick creamy base.",
      "Turn off the heat. Immediately stir in butter until melted.",
      "Fold in shredded cheese one handful at a time until completely smooth and luscious.",
      "Season with freshly cracked black pepper and enjoy warm."
    ]
  },
  {
    id: "rec-22",
    title: "Quick Black Bean Sweet Corn Fiesta Bowl",
    category: "Lunch",
    cuisine: "Mexican",
    mealType: "Lunch",
    difficulty: "Easy",
    prepTime: 8,
    cookTime: 0,
    servings: 2,
    calories: 340,
    macros: { protein: "12g", carbs: "54g", fat: "9g" },
    diet: ["Vegetarian", "Vegan", "Gluten-Free"],
    rating: 4.79,
    reviewsCount: 79,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    description: "A bright, zesty fiesta bowl made with canned black beans, sweet corn, diced avocado, red onion, tomatoes, and lime juice.",
    wasteReductionTip: "No cooking needed! Pack into meal-prep containers for work or school lunches—it stays crunchy for 3 days.",
    ingredients: [
      { name: "black beans", amount: 1.5, unit: "cups", original: "1 can (15 oz) black beans, drained" },
      { name: "corn", amount: 1, unit: "cup", original: "1 cup sweet corn (canned or thawed frozen)" },
      { name: "avocado", amount: 1, unit: "medium", original: "1 ripe avocado, diced" },
      { name: "tomato", amount: 1, unit: "cup", original: "1 cup diced tomatoes" },
      { name: "onion", amount: 0.5, unit: "cup", original: "1/2 red onion, finely chopped" },
      { name: "lemon", amount: 1, unit: "whole", original: "1 lime or lemon, juiced" },
      { name: "olive oil", amount: 1, unit: "tbsp", original: "1 tbsp olive oil" }
    ],
    instructions: [
      "In a large bowl, combine rinsed black beans, sweet corn, diced tomatoes, and red onion.",
      "Drizzle with fresh lime juice, olive oil, salt, cumin, and cracked black pepper.",
      "Toss well to distribute flavors evenly.",
      "Gently fold in diced avocado and fresh cilantro right before serving.",
      "Eat as a power salad or scoop with crispy tortilla chips."
    ]
  },
  {
    id: "rec-23",
    title: "Crispy Potato Hash with Fried Sunny Eggs",
    category: "Breakfast",
    cuisine: "American Diner",
    mealType: "Breakfast",
    difficulty: "Easy",
    prepTime: 8,
    cookTime: 15,
    servings: 2,
    calories: 370,
    macros: { protein: "14g", carbs: "38g", fat: "18g" },
    diet: ["Vegetarian", "Gluten-Free"],
    rating: 4.89,
    reviewsCount: 147,
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    description: "Diner-style crispy diced skillet potatoes tossed with caramelized onions and bell peppers, crowned with sunny-side up eggs.",
    wasteReductionTip: "Cut potatoes evenly into small 1/2-inch cubes for faster, crispier cooking without pre-boiling.",
    ingredients: [
      { name: "potato", amount: 3, unit: "medium", original: "3 medium russet or yellow potatoes, diced small" },
      { name: "egg", amount: 2, unit: "large", original: "2-4 large eggs" },
      { name: "onion", amount: 1, unit: "medium", original: "1 onion, diced" },
      { name: "bell pepper", amount: 1, unit: "medium", original: "1 bell pepper, diced" },
      { name: "butter", amount: 2, unit: "tbsp", original: "2 tbsp butter or oil" },
      { name: "garlic", amount: 2, unit: "cloves", original: "2 cloves garlic, minced" }
    ],
    instructions: [
      "Heat butter and oil in a large skillet over medium-high heat.",
      "Add diced potatoes in an even layer. Let them cook undisturbed for 5 minutes so a deep golden crust forms.",
      "Toss potatoes, then add diced onions, bell peppers, garlic, salt, and smoked paprika.",
      "Cook for another 8-10 minutes, tossing every few minutes, until potatoes are tender inside and crispy outside.",
      "Create small pockets in the hash and crack eggs directly in, or fry eggs separately in butter.",
      "Cook until egg whites are set and yolks are runny. Season with flaky salt."
    ]
  },
  {
    id: "rec-24",
    title: "15-Minute Sweet & Tangy Honey Soy Tofu Bowl",
    category: "Dinner",
    cuisine: "Asian",
    mealType: "Dinner",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 360,
    macros: { protein: "20g", carbs: "38g", fat: "14g" },
    diet: ["Vegetarian", "High-Protein"],
    rating: 4.83,
    reviewsCount: 82,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    description: "Crispy pan-fried tofu cubes tossed in a glossy glaze of honey, soy sauce, garlic, and vinegar over fluffy rice.",
    wasteReductionTip: "Tofu easily absorbs whatever marinade or sauce you coat it with—no marinating time required.",
    ingredients: [
      { name: "tofu", amount: 350, unit: "g", original: "350g firm tofu, pressed and cut into cubes" },
      { name: "rice", amount: 2, unit: "cups", original: "2 cups cooked white or brown rice" },
      { name: "soy sauce", amount: 3, unit: "tbsp", original: "3 tbsp soy sauce" },
      { name: "honey", amount: 2, unit: "tbsp", original: "2 tbsp honey or maple syrup" },
      { name: "garlic", amount: 2, unit: "cloves", original: "2 cloves garlic, minced" },
      { name: "olive oil", amount: 2, unit: "tbsp", original: "2 tbsp cooking oil" }
    ],
    instructions: [
      "Whisk soy sauce, honey, minced garlic, and 1 tbsp water in a small bowl.",
      "Heat oil in a skillet over high heat. Add tofu cubes and pan-fry for 6-8 minutes, turning until crispy on all sides.",
      "Pour glaze directly over the crispy tofu. Stir constantly for 1-2 minutes until sauce thickens and glazes each cube.",
      "Serve immediately over warm bowls of rice, topped with sesame seeds."
    ]
  }
];

// Attach to window
window.RECIPES_DATA = RECIPES_DATA;
window.COMMON_PANTRY_INGREDIENTS = COMMON_PANTRY_INGREDIENTS;
window.INGREDIENT_SUBSTITUTIONS = INGREDIENT_SUBSTITUTIONS;
